<a href="https://colab.research.google.com/github/nespina/AIandDataScienceWorkshopwithPython/blob/main/Week2/Assignment/Assignment_Numpy_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#AI and Data Science Workshop with Python
Introduction to Numpy


Assignment 01


1- Create a NumPy array and test whether any elements of the array are non-zero
a sample output can be like this:
```
[1 2 3 4]
True
[0 1 2 3]
False
```

In [3]:
import numpy as np
a = np.arange (1,5)
print (a)
print(np.all(a)) 
b = np.arange(4)
print(b)
print(np.all(b))
#any (any are nonzero)
#all (all are nonzero)

[1 2 3 4]
True
[0 1 2 3]
False


In [5]:
a= np.array([0,0,0,0])
print(np.any(a))


False


In [6]:
a= np.array([0,0,0,3])
print (np.any(a))

True


In [8]:
b= np.array([2,3,4])
print(np.isin(8,b))
print(np.isin(4,b))

False
True


2- Create a NumPy array of integer in range of 30 to 70
the result can be as follow:
```
Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
 ```


In [41]:
print ("Array of the intergers from 30 to 70") 
print(np.arange(30,71))

Array of the intergers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


3- Create two NumPy array with the same number of elements and compare them to see if their elements are equal. you can use `equal()` function

A sample result can be as follow:
Original numbers:
```
[ 12  43  56  14  67  -1 120 -12  60  10]
[ 12.        43.        56.        14.        67.        -1.
 120.       -12.        60.        10.000001]
Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
```

In [40]:
b= np.array([12,43,56,14,67,-1,120,-12,60,10])
print (b)
c= [12,43,56,14,67,-1,120,-12,60,10.000001]
print(np.asanyarray (c))
print("Comparison -equal:")
print(np.equal(b,c))

[ 12  43  56  14  67  -1 120 -12  60  10]
[ 12.        43.        56.        14.        67.        -1.
 120.       -12.        60.        10.000001]
Comparison -equal:
[ True  True  True  True  True  True  True  True  True False]


In [ ]:
#reshape to 3 rows and 2 columns
#reshaping
a = np.arange(6).reshape((3, 2))
print(a)

[[0 1]
 [2 3]
 [4 5]]


4- Write a NumPy program to create a 3X4 array and iterate over it to print the items

In [52]:
arr = np.array([[1, 1,1,1], [2, 2,2,2], [3,3,3, 3]])
for x in arr:
  print(x)

[1 1 1 1]
[2 2 2 2]
[3 3 3 3]


5- Using NumPy, create a 4x5 matrix filled with values from 1 to 20

In [53]:
n= np.arange (1,21).reshape ((4,5))
print(n)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


6- We have created a matrix of size 5x4 as follow:

In [10]:
import numpy as np
sizes = np.array(
[[2,  8, 8, 3],
[6,  13, 1, 6],
[9,  5, 3, 7],
[3,  22, 9, 2],
[12, 7, 2, 9]])

Write a NumPy code that retrieves the last column of sizes matrix:

In [3]:
print(sizes[:, 3])

[3 6 7 2 9]


Write a Numpy code that retrieves the following submatrix from `sizes`:

```
array([[13,  1],
       [ 5,  3]])
```

In [11]:
#sizes[[1,1],[1,2]],sizes[[2,2],[2,2]]
#sizes[np.ix_([1,2],[1,2])]
sizes[1:3,1:3]

array([[13,  1],
       [ 5,  3]])

Write a NumPy program that in result create an array containing such items of the sizes matrix, which are greater than 10

In [43]:
#print (sizes)
sizes[sizes>10]

array([13, 22, 12])